/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_doubleslash_demo_coverage_module_five_JniWrapper */

#ifndef _Included_de_doubleslash_demo_coverage_module_five_JniWrapper
#define _Included_de_doubleslash_demo_coverage_module_five_JniWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_doubleslash_demo_coverage_module_five_JniWrapper
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_doubleslash_demo_coverage_module_five_JniWrapper_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
